//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeThing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool twentyfourmode {
            get {
                return ((bool)(this["twentyfourmode"]));
            }
            set {
                this["twentyfourmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double BaseTimeZone {
            get {
                return ((double)(this["BaseTimeZone"]));
            }
            set {
                this["BaseTimeZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double OffsetTimeZone {
            get {
                return ((double)(this["OffsetTimeZone"]));
            }
            set {
                this["OffsetTimeZone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BR")]
        public string WidgetPos {
            get {
                return ((string)(this["WidgetPos"]));
            }
            set {
                this["WidgetPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("213, 186, 181")]
        public global::System.Drawing.Color MainColour {
            get {
                return ((global::System.Drawing.Color)(this["MainColour"]));
            }
            set {
                this["MainColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87, 77, 104")]
        public global::System.Drawing.Color AccentColour {
            get {
                return ((global::System.Drawing.Color)(this["AccentColour"]));
            }
            set {
                this["AccentColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("106, 141, 115")]
        public global::System.Drawing.Color TimesColour {
            get {
                return ((global::System.Drawing.Color)(this["TimesColour"]));
            }
            set {
                this["TimesColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("147, 198, 214")]
        public global::System.Drawing.Color TxtColour {
            get {
                return ((global::System.Drawing.Color)(this["TxtColour"]));
            }
            set {
                this["TxtColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("211, 97, 53")]
        public global::System.Drawing.Color DisplayTextColour {
            get {
                return ((global::System.Drawing.Color)(this["DisplayTextColour"]));
            }
            set {
                this["DisplayTextColour"] = value;
            }
        }
    }
}
